-- Criacao do banco
CREATE DATABASE BD_UNIP_2024;
-- Colocar o banco em uso
use BD_UNIP_2024;
-- Criar tabela
CREATE TABLE TESTE01(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATANASC DATE NOT NULL,
	PESO FLOAT NOT NULL,
	HORACADASTRO TIME NOT NULL,
);
--Inserir dados na tabela
INSERT INTO TESTE01 VALUES(
'ROBERTO CARLOS',
'M',
'12-25-1950',
59.00,
'21:10'
);

INSERT INTO TESTE01 VALUES(
'ANGELICA HULK',
'F',
'12-25-1950',
65.00,
'22:20'
);

--Selecionar tabela
SELECT*FROM TESTE01;
--Dropar (excluir) tabela
--DROP TABLE TESTE01

--Alterando a tabela
ALTER TABLE TESTE01 ADD EMAIL VARCHAR(50);

INSERT INTO TESTE01 VALUES(
'SILVIO SANTOS',
'M',
'12-12-1940',
50.00,
'23:30',
'SilvioSantos@sbt.com'
);
