CREATE DATABASE ECOMMERCE_VITORIA
USE ECOMMERCE_VITORIA
--DROP DATABASE ECOMMERCE_VITORIA

CREATE TABLE TB_LINHA(
ID_TB_LINHA INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO_LINHA VARCHAR(50) NOT NULL,
)

INSERT INTO TB_LINHA VALUES(
'IPHONE'
)
INSERT INTO TB_LINHA VALUES(
'GALAXY'
)
INSERT INTO TB_LINHA VALUES(
'PIXEL'
)
INSERT INTO TB_LINHA VALUES(
'XPERIA'
)
INSERT INTO TB_LINHA VALUES(
'ONEPLUS'
)
INSERT INTO TB_LINHA VALUES(
'MI'
)
INSERT INTO TB_LINHA VALUES(
'REDMI'
)
INSERT INTO TB_LINHA VALUES(
'MOTO'
)
INSERT INTO TB_LINHA VALUES(
'NOKIA X'
)
INSERT INTO TB_LINHA VALUES(
'HUAWEI P40'
)
CREATE TABLE TB_MARCA(
ID_TB_MARCA INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO_MARCA VARCHAR(50) NOT NULL
)

INSERT INTO TB_MARCA VALUES(
'APPLE'
)
INSERT INTO TB_MARCA VALUES(
'SAMSUNG'
)
INSERT INTO TB_MARCA VALUES(
'GOOGLE'
)
INSERT INTO TB_MARCA VALUES(
'SONY'
)
INSERT INTO TB_MARCA VALUES(
'ONEPLUS'
)
INSERT INTO TB_MARCA VALUES(
'XIAOMI'
)
INSERT INTO TB_MARCA VALUES(
'MOTOROLA'
)
INSERT INTO TB_MARCA VALUES(
'HUAWEI'
)
INSERT INTO TB_MARCA VALUES(
'LG'
)
INSERT INTO TB_MARCA VALUES(
'NOKIA'
)
CREATE TABLE TB_PRODUTO(
ID_TB_PRODUTO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_LINHA INT NOT NULL,
ID_TB_MARCA INT NOT NULL,
DESCRICAO VARCHAR(30) NOT NULL,

FOREIGN KEY (ID_TB_LINHA) REFERENCES TB_LINHA,
FOREIGN KEY (ID_TB_MARCA) REFERENCES TB_MARCA
)

INSERT INTO TB_PRODUTO VALUES(
1,
1,
'IPHONE 13'
)
INSERT INTO TB_PRODUTO VALUES(
2,
2,
'SAMSUNG GALAXY S21'
)
INSERT INTO TB_PRODUTO VALUES(
3,
3,
'GOOGLE PIXEL 6'
)
INSERT INTO TB_PRODUTO VALUES(
4,
4,
'SONY XPERIA 1 III'
)
INSERT INTO TB_PRODUTO VALUES(
5,
5,
'ONE PLUS 9 PRO'
)
INSERT INTO TB_PRODUTO VALUES(
6,
6,
'XIAOMI MI 11'
)
INSERT INTO TB_PRODUTO VALUES(
10,
8,
'HUAWEI P40 PRO'
)
INSERT INTO TB_PRODUTO VALUES(
7,
6,
'REDMI NOTE 11'
)
INSERT INTO TB_PRODUTO VALUES(
8,
7,
'MOTOROLA EDGE +'
)
INSERT INTO TB_PRODUTO VALUES(
9,
10,
'NOKIA X20'
)
CREATE TABLE TB_ITEM_PEDIDO(
ID_TB_ITEM_PEDIDO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PRODUTO INT NOT NULL,
PRECO DECIMAL(18,4) NOT NULL,
QUANTIDADE INT NOT NULL,

FOREIGN KEY (ID_TB_PRODUTO) REFERENCES TB_PRODUTO
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
1,
3700,
1
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
2,
4200,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
3,
3000,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
4,
6300,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
5,
5100,
3
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
6,
4000,
5
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
7,
5100,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
8,
1050,
7
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
9,
5300,
10
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
10,
1750,
2
)
CREATE TABLE TB_CLIENTE(
ID_TB_CLIENTE INT IDENTITY NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
CPF VARCHAR(11) NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
)

INSERT INTO TB_CLIENTE VALUES(
'VITORIA APARECIDA',
'vitoria@email.com',
'123345434',
'RUA DAS ARVORES, 10, BAIRRO 1, CIDADE 2, SP'
)

CREATE TABLE TB_TIPO_MOVIMENTACAO(
ID_TB_TIPO_MOVIMENTACAO INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(10) NOT NULL,
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'COMPRA'
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'DEVOLUCAO'
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'VENDA'
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'TROCA'
)

CREATE TABLE TB_MOVIMENTO(
ID_TB_MOVIMENTO INT IDENTITY NOT NULL PRIMARY KEY,
DATA_MOVIMENTO VARCHAR(20) NOT NULL,
MOV_ENTRADA_SAIDA VARCHAR(10) NOT NULL,
ID_TB_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
ID_TB_TIPO_MOVIMENTACAO INT NOT NULL,

FOREIGN KEY(ID_TB_PRODUTO) REFERENCES TB_PRODUTO,
FOREIGN KEY(ID_TB_TIPO_MOVIMENTACAO) REFERENCES TB_TIPO_MOVIMENTACAO
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-04-30',
'ENTRADA',
1,
200,
1
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-04-30',
'SAIDA',
1,
10,
2
)

CREATE TABLE TB_PEDIDO(
ID_TB_PEDIDO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_CLIENTE INT NOT NULL,
DATA_PEDIDO VARCHAR(20) NOT NULL

FOREIGN KEY (ID_TB_CLIENTE) REFERENCES TB_CLIENTE,
)

INSERT INTO TB_PEDIDO VALUES(
1,
'2024-04-30'
)

CREATE TABLE TB_ESTOQUE(
ID_TB_ESTOQUE INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
ESTOQUE_MINIMO INT NOT NULL,
ESTOQUE_MAXIMO INT NOT NULL

FOREIGN KEY (ID_TB_PRODUTO) REFERENCES TB_PRODUTO
)

INSERT INTO TB_ESTOQUE VALUES(
1,
100,
50,
500
)

CREATE TABLE TB_FORMA_PAGAMENTO(
ID_TB_FORMA_PAGAMENTO INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(20) NOT NULL
)

INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'DINHEIRO'
)
INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'PIX'
)
INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'DEBITO'
)
INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'CREDITO'
)

CREATE TABLE TB_PAGAMENTO(
ID_TB_PAGAMENTO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PEDIDO INT NOT NULL,
ID_TB_FORMA_PAGAMENTO INT NOT NULL,

FOREIGN KEY (ID_TB_PEDIDO) REFERENCES TB_PEDIDO,
FOREIGN KEY(ID_TB_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO
)

INSERT INTO TB_PAGAMENTO VALUES(
1,
1
)

SELECT*FROM TB_PEDIDO
SELECT*FROM TB_ITEM_PEDIDO
SELECT*FROM TB_PRODUTO
SELECT*FROM TB_TIPO_MOVIMENTACAO
SELECT*FROM TB_MOVIMENTO
SELECT*FROM TB_ESTOQUE
SELECT*FROM TB_LINHA
