CREATE DATABASE ECOMMERCE_VITORIA
USE ECOMMERCE_VITORIA
--DROP DATABASE ECOMMERCE_VITORIA

CREATE TABLE TB_LINHA(
ID_TB_LINHA INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO_LINHA VARCHAR(50) NOT NULL,
)

INSERT INTO TB_LINHA VALUES(
'IPHONE'
)
INSERT INTO TB_LINHA VALUES(
'GALAXY'
)
INSERT INTO TB_LINHA VALUES(
'PIXEL'
)
INSERT INTO TB_LINHA VALUES(
'XPERIA'
)
INSERT INTO TB_LINHA VALUES(
'ONEPLUS'
)
INSERT INTO TB_LINHA VALUES(
'MI'
)
INSERT INTO TB_LINHA VALUES(
'REDMI'
)
INSERT INTO TB_LINHA VALUES(
'MOTO'
)
INSERT INTO TB_LINHA VALUES(
'NOKIA X'
)
INSERT INTO TB_LINHA VALUES(
'HUAWEI P40'
)
CREATE TABLE TB_MARCA(
ID_TB_MARCA INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO_MARCA VARCHAR(50) NOT NULL
)

INSERT INTO TB_MARCA VALUES(
'APPLE'
)
INSERT INTO TB_MARCA VALUES(
'SAMSUNG'
)
INSERT INTO TB_MARCA VALUES(
'GOOGLE'
)
INSERT INTO TB_MARCA VALUES(
'SONY'
)
INSERT INTO TB_MARCA VALUES(
'ONEPLUS'
)
INSERT INTO TB_MARCA VALUES(
'XIAOMI'
)
INSERT INTO TB_MARCA VALUES(
'MOTOROLA'
)
INSERT INTO TB_MARCA VALUES(
'HUAWEI'
)
INSERT INTO TB_MARCA VALUES(
'LG'
)
INSERT INTO TB_MARCA VALUES(
'NOKIA'
)
CREATE TABLE TB_PRODUTO(
ID_TB_PRODUTO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_LINHA INT NOT NULL,
ID_TB_MARCA INT NOT NULL,
DESCRICAO VARCHAR(30) NOT NULL,

FOREIGN KEY (ID_TB_LINHA) REFERENCES TB_LINHA,
FOREIGN KEY (ID_TB_MARCA) REFERENCES TB_MARCA
)

INSERT INTO TB_PRODUTO VALUES(
1,
1,
'IPHONE 13'
)
INSERT INTO TB_PRODUTO VALUES(
2,
2,
'SAMSUNG GALAXY S21'
)
INSERT INTO TB_PRODUTO VALUES(
3,
3,
'GOOGLE PIXEL 6'
)
INSERT INTO TB_PRODUTO VALUES(
4,
4,
'SONY XPERIA 1 III'
)
INSERT INTO TB_PRODUTO VALUES(
5,
5,
'ONE PLUS 9 PRO'
)
INSERT INTO TB_PRODUTO VALUES(
6,
6,
'XIAOMI MI 11'
)
INSERT INTO TB_PRODUTO VALUES(
10,
8,
'HUAWEI P40 PRO'
)
INSERT INTO TB_PRODUTO VALUES(
7,
6,
'REDMI NOTE 11'
)
INSERT INTO TB_PRODUTO VALUES(
8,
7,
'MOTOROLA EDGE +'
)
INSERT INTO TB_PRODUTO VALUES(
9,
10,
'NOKIA X20'
)
CREATE TABLE TB_ITEM_PEDIDO(
ID_TB_ITEM_PEDIDO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PRODUTO INT NOT NULL,
PRECO DECIMAL(18,4) NOT NULL,
QUANTIDADE INT NOT NULL,

FOREIGN KEY (ID_TB_PRODUTO) REFERENCES TB_PRODUTO
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
1,
3700,
1
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
2,
4200,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
3,
3000,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
4,
6300,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
5,
5100,
3
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
6,
4000,
5
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
7,
5100,
2
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
8,
1050,
7
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
9,
5300,
10
)
INSERT INTO TB_ITEM_PEDIDO VALUES(
10,
1750,
2
)
CREATE TABLE TB_CLIENTE(
ID_TB_CLIENTE INT IDENTITY NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
)

INSERT INTO TB_CLIENTE VALUES(
'VITORIA APARECIDA',
'vitoria@email.com',
'258-325-782-25',
'RUA DAS ARVORES, 10, BAIRRO 1, CIDADE 2, SP'
)
INSERT INTO TB_CLIENTE VALUES(
'ROBERTO ALVES',
'roberto@email.com',
'456-789-132-58',
'RUA DAS MELANCIAS, 187, BAIRRO 2, CIDADE 3, SP'
)
INSERT INTO TB_CLIENTE VALUES(
'ANA MARIA',
'ana@email.com',
'724-258-052-96',
'RUA DAS ABOBORAS, 852, BAIRRO 3, CIDADE 4, RJ'
)
INSERT INTO TB_CLIENTE VALUES(
'AMANDA SOUZA',
'amanda@email.com',
'265-402-447-01',
'RUA DAS PERAS, 2, BAIRRO 4, CIDADE 5, RN'
)
INSERT INTO TB_CLIENTE VALUES(
'JORGE RODRIGO',
'jorge@email.com',
'025-721-349-55',
'RUA DOS ABACATES, 78, BAIRRO 5, CIDADE 6, GO'
)
INSERT INTO TB_CLIENTE VALUES(
'BEATRIZ ALMEIDA',
'beatriz@email.com',
'112-027-876-29',
'RUA DAS LARANJAS, 24, BAIRRO 6, CIDADE 7, SP'
)
INSERT INTO TB_CLIENTE VALUES(
'LAURA SILVA',
'laura@email.com',
'327-072-005-71',
'RUA DOS LIMOES, 4, BAIRRO 7, CIDADE 8, RS'
)
INSERT INTO TB_CLIENTE VALUES(
'JOSE ROBERTO',
'jose@email.com',
'124-008-567-72',
'RUA DAS JABUTICABAS, 247, BAIRRO 8, CIDADE 9, ES'
)
INSERT INTO TB_CLIENTE VALUES(
'GABRIEL BRITO',
'gabriel@email.com',
'048-412-127-74',
'RUA DOS KIWIS, 71, BAIRRO 9, CIDADE 10, SP'
)
INSERT INTO TB_CLIENTE VALUES(
'RODRIGO SANTOS',
'rogrigo@email.com',
'112-047-226-00',
'RUA DAS UVAS, 57, BAIRRO 10, CIDADE 11, PR'
)
CREATE TABLE TB_TIPO_MOVIMENTACAO(
ID_TB_TIPO_MOVIMENTACAO INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(10) NOT NULL,
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'COMPRA'
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'DEVOLUCAO'
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'VENDA'
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'TROCA'
)

CREATE TABLE TB_MOVIMENTO(
ID_TB_MOVIMENTO INT IDENTITY NOT NULL PRIMARY KEY,
DATA_MOVIMENTO VARCHAR(20) NOT NULL,
MOV_ENTRADA_SAIDA VARCHAR(10) NOT NULL,
ID_TB_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
ID_TB_TIPO_MOVIMENTACAO INT NOT NULL,

FOREIGN KEY(ID_TB_PRODUTO) REFERENCES TB_PRODUTO,
FOREIGN KEY(ID_TB_TIPO_MOVIMENTACAO) REFERENCES TB_TIPO_MOVIMENTACAO
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-04-30',
'ENTRADA',
1,
200,
1
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-05-02',
'SAIDA',
2,
100,
4
)
INSERT INTO TB_MOVIMENTO VALUES(
'2024-05-10',
'ENTRADA',
3,
300,
2
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-05-08',
'SAIDA',
4,
400,
3
)
INSERT INTO TB_MOVIMENTO VALUES(
'2024-05-25',
'ENTRADA',
5,
700,
1
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-06-05',
'SAIDA',
6,
100,
3
)
INSERT INTO TB_MOVIMENTO VALUES(
'2024-06-10',
'ENTRADA',
7,
200,
2
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-06-15',
'SAIDA',
8,
100,
4
)
INSERT INTO TB_MOVIMENTO VALUES(
'2024-06-20',
'ENTRADA',
9,
200,
1
)

INSERT INTO TB_MOVIMENTO VALUES(
'2024-05-21',
'SAIDA',
10,
100,
3
)
INSERT INTO TB_MOVIMENTO VALUES(
'2024-05-22',
'ENTRADA',
1,
300,
2
)

CREATE TABLE TB_PEDIDO(
ID_TB_PEDIDO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_CLIENTE INT NOT NULL,
DATA_PEDIDO VARCHAR(20) NOT NULL

FOREIGN KEY (ID_TB_CLIENTE) REFERENCES TB_CLIENTE,
)

INSERT INTO TB_PEDIDO VALUES(
1,
'2024-04-30'
)
INSERT INTO TB_PEDIDO VALUES(
2,
'2024-05-01'
)
INSERT INTO TB_PEDIDO VALUES(
3,
'2024-05-02'
)
INSERT INTO TB_PEDIDO VALUES(
4,
'2024-05-03'
)
INSERT INTO TB_PEDIDO VALUES(
5,
'2024-05-04'
)
INSERT INTO TB_PEDIDO VALUES(
6,
'2024-05-05'
)
INSERT INTO TB_PEDIDO VALUES(
7,
'2024-05-06'
)
INSERT INTO TB_PEDIDO VALUES(
8,
'2024-05-07'
)
INSERT INTO TB_PEDIDO VALUES(
9,
'2024-05-08'
)
INSERT INTO TB_PEDIDO VALUES(
10,
'2024-05-09'
)
CREATE TABLE TB_ESTOQUE(
ID_TB_ESTOQUE INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
ESTOQUE_MINIMO INT NOT NULL,
ESTOQUE_MAXIMO INT NOT NULL

FOREIGN KEY (ID_TB_PRODUTO) REFERENCES TB_PRODUTO
)

INSERT INTO TB_ESTOQUE VALUES(
1,
1000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
2,
2000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
3,
3000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
4,
4000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
5,
5000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
6,
6000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
7,
7000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
8,
7000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
9,
8000,
50,
1000000
)
INSERT INTO TB_ESTOQUE VALUES(
10,
9000,
50,
1000000
)
CREATE TABLE TB_FORMA_PAGAMENTO(
ID_TB_FORMA_PAGAMENTO INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(20) NOT NULL
)

INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'DINHEIRO'
)
INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'PIX'
)
INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'DEBITO'
)
INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'CREDITO'
)

CREATE TABLE TB_PAGAMENTO(
ID_TB_PAGAMENTO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PEDIDO INT NOT NULL,
ID_TB_FORMA_PAGAMENTO INT NOT NULL,

FOREIGN KEY (ID_TB_PEDIDO) REFERENCES TB_PEDIDO,
FOREIGN KEY(ID_TB_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO
)

INSERT INTO TB_PAGAMENTO VALUES(
1,
1
)
INSERT INTO TB_PAGAMENTO VALUES(
2,
2
)
INSERT INTO TB_PAGAMENTO VALUES(
3,
3
)
INSERT INTO TB_PAGAMENTO VALUES(
4,
4
)
INSERT INTO TB_PAGAMENTO VALUES(
5,
1
)
INSERT INTO TB_PAGAMENTO VALUES(
6,
2
)
INSERT INTO TB_PAGAMENTO VALUES(
7,
3
)
INSERT INTO TB_PAGAMENTO VALUES(
8,
4
)
INSERT INTO TB_PAGAMENTO VALUES(
9,
1
)
INSERT INTO TB_PAGAMENTO VALUES(
10,
2
)

UPDATE TB_PRODUTO
SET DESCRICAO = 'SAMSUNG GALAXY S23'
WHERE ID_TB_PRODUTO = 2

--BUSCAR PRODUTOS TRAZENDO A DESCRICAO DA LINHA E MARCA
SELECT ID_TB_PRODUTO, TB_LINHA.DESCRICAO_LINHA, TB_MARCA.DESCRICAO_MARCA, DESCRICAO 
FROM TB_PRODUTO
JOIN TB_LINHA
ON TB_PRODUTO.ID_TB_LINHA = TB_LINHA.ID_TB_LINHA
JOIN TB_MARCA
ON TB_PRODUTO.ID_TB_MARCA = TB_MARCA.ID_TB_MARCA

-- BUSCAR O PEDIDO TRAZENDO O NOME DO CLIENTE
SELECT ID_TB_PEDIDO, TB_CLIENTE.NOME, DATA_PEDIDO
FROM TB_PEDIDO
JOIN TB_CLIENTE
ON TB_PEDIDO.ID_TB_CLIENTE = TB_CLIENTE.ID_TB_CLIENTE

-- BUSCAR O ITEM DO PEDIDO TRAZENDO A DESCRICAO DO PRODUTO
SELECT ID_TB_ITEM_PEDIDO, TB_PRODUTO.DESCRICAO, PRECO, QUANTIDADE
FROM TB_ITEM_PEDIDO
JOIN TB_PRODUTO
ON TB_ITEM_PEDIDO.ID_TB_PRODUTO = TB_PRODUTO.ID_TB_PRODUTO

SELECT*FROM TB_PRODUTO
SELECT*FROM TB_PEDIDO
SELECT*FROM TB_ITEM_PEDIDO
SELECT*FROM TB_TIPO_MOVIMENTACAO
SELECT*FROM TB_MOVIMENTO
SELECT*FROM TB_ESTOQUE
SELECT*FROM TB_LINHA
SELECT*FROM TB_CLIENTE
