create database ECOMMERCE_VITORIA
use ECOMMERCE_VITORIA

CREATE TABLE TB_LINHA(
ID_TB_LINHA INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO_LINHA VARCHAR(50) NOT NULL,
COR VARCHAR(20) NOT NULL
)

INSERT INTO TB_LINHA VALUES(
'LINHA BOA',
'AZUL'
)

CREATE TABLE TB_MARCA(
ID_TB_MARCA INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO_MARCA VARCHAR(50) NOT NULL
)

INSERT INTO TB_MARCA VALUES(
'SAMSUNG'
)

CREATE TABLE TB_PRODUTO(
ID_TB_PRODUTO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_LINHA INT NOT NULL,
ID_TB_MARCA INT NOT NULL,
DESCRICAO VARCHAR(30) NOT NULL,
PRECO FLOAT NOT NULL

FOREIGN KEY (ID_TB_LINHA) REFERENCES TB_LINHA,
FOREIGN KEY (ID_TB_MARCA) REFERENCES TB_MARCA
)

INSERT INTO TB_PRODUTO VALUES(
1,
1,
'CELULAR',
2.500
)

CREATE TABLE TB_ITEM_PEDIDO(
ID_TB_ITEM_PEDIDO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PRODUTO INT NOT NULL,

FOREIGN KEY (ID_TB_PRODUTO) REFERENCES TB_PRODUTO
)

INSERT INTO TB_ITEM_PEDIDO VALUES(
1
)

CREATE TABLE TB_CLIENTE(
ID_TB_CLIENTE INT IDENTITY NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
CPF VARCHAR(11) NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
)

INSERT INTO TB_CLIENTE VALUES(
'VITORIA APARECIDA',
'vitoria@email.com',
'123345434',
'RUA DAS ARVORES, 10, BAIRRO 1, CIDADE 2, SP'
)

CREATE TABLE TB_MOVIMENTO(
ID_TB_MOVIMENTO INT IDENTITY NOT NULL PRIMARY KEY,
MOVIMENTO VARCHAR(10) NOT NULL
)

INSERT INTO TB_MOVIMENTO VALUES(
'ENTRADA'
)

INSERT INTO TB_MOVIMENTO VALUES(
'SAIDA'
)

CREATE TABLE TB_TIPO_MOVIMENTACAO(
ID_TB_TIPO_MOVIMENTACAO INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(10) NOT NULL,
ID_TB_MOVIMENTO INT NOT NULL
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'COMPRA',
1
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'DEVOLUCAO',
1
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'VENDA',
2
)

INSERT INTO TB_TIPO_MOVIMENTACAO VALUES(
'TROCA',
2
)

CREATE TABLE TB_PEDIDO(
ID_TB_PEDIDO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_ITEM_PEDIDO INT NOT NULL,
ID_TB_CLIENTE INT NOT NULL,
ID_TIPO_MOVIMENTACAO INT NOT NULL,

FOREIGN KEY (ID_TB_CLIENTE) REFERENCES TB_CLIENTE,
FOREIGN KEY (ID_TB_ITEM_PEDIDO) REFERENCES TB_ITEM_PEDIDO,
FOREIGN KEY (ID_TIPO_MOVIMENTACAO) REFERENCES TB_TIPO_MOVIMENTACAO
)

INSERT INTO TB_PEDIDO VALUES(
1,
1,
1
)

CREATE TABLE TB_ESTOQUE(
ID_TB_ESTOQUE INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
ESTOQUE_MINIMO INT NOT NULL,

FOREIGN KEY (ID_TB_PRODUTO) REFERENCES TB_PRODUTO
)

INSERT INTO TB_ESTOQUE VALUES(
1,
100,
50
)

CREATE TABLE TB_FORMA_PAGAMENTO(
ID_TB_FORMA_PAGAMENTO INT IDENTITY NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(20) NOT NULL
)

INSERT INTO TB_FORMA_PAGAMENTO VALUES(
'DINHEIRO'
)

CREATE TABLE TB_PAGAMENTO(
ID_TB_PAGAMENTO INT IDENTITY NOT NULL PRIMARY KEY,
ID_TB_PEDIDO INT NOT NULL,
ID_TB_FORMA_PAGAMENTO INT NOT NULL,

FOREIGN KEY (ID_TB_PEDIDO) REFERENCES TB_PEDIDO,
FOREIGN KEY(ID_TB_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO
)

INSERT INTO TB_PAGAMENTO VALUES(
1,
1
)

SELECT*FROM TB_PEDIDO
SELECT*FROM TB_ITEM_PEDIDO
SELECT*FROM TB_PRODUTO
SELECT*FROM TB_TIPO_MOVIMENTACAO
SELECT*FROM TB_MOVIMENTO
